services:

  nextjudge-data-layer-dev:
    extends:
      file: ../src/data-layer/docker-compose.dev.yml
      service: nextjudge-data-layer-dev
    environment:
      - ELASTIC_ENDPOINT=http://elasticsearch:9200
      - ELASTIC_ENABLED="${ELASTIC_ENABLED:-false}"
      - JUDGE_PASSWORD=${JUDGE_PASSWORD}
      - JWT_SIGNING_SECRET=${JWT_SIGNING_SECRET}
      - AUTH_PROVIDER_PASSWORD=${AUTH_PROVIDER_PASSWORD}
      - DB_HOST=db-dev
      - DB_PASSWORD=${AUTH_PROVIDER_PASSWORD}
      - RABBITMQ_HOST=rabbitmq-dev
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - AUTH_DISABLED=false
      - SEED_DATA=true
    depends_on:
      db-dev:
        condition: service_healthy
      rabbitmq-dev:
        condition: service_healthy
      # elasticsearch:
    #     # condition: service_healthy

  db-dev:
    extends:
      file: ../src/data-layer/docker-compose.db.yml
      service: db
    environment:
      - POSTGRES_PASSWORD=${AUTH_PROVIDER_PASSWORD}

  nextjudge-judge-dev:
    extends:
      file: ../src/judge/docker-compose.dev.yml
      service: nextjudge-judge-dev
    environment:
      - RABBITMQ_HOST=rabbitmq-dev
      - RABBITMQ_PORT=5672
      - NEXTJUDGE_HOST=nextjudge-data-layer-dev
      - NEXTJUDGE_PORT=5000
      - JUDGE_PASSWORD=${JUDGE_PASSWORD}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    profiles: [judge]
    depends_on:
      rabbitmq-dev:
        condition: service_healthy
      nextjudge-data-layer-dev:
        condition: service_healthy

  rabbitmq-dev:
    extends:
      file: ../src/data-layer/docker-compose.rabbitmq.yml
      service: rabbitmq
    environment:
      - RABBITMQ_LOGS="error"
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

  # elasticsearch:
  #   extends:
  #     file: src/data-layer/docker-compose.elasticsearch.yml
  #     service: elasticsearch
  #   profiles: [elastic]

volumes:
  postgres_data:
  go_cache:
  go_mod_cache:
