name: Build and Push Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/docker-build-push.yaml'
      - 'src/data-layer/**'
      - 'src/judge/**'
      - 'docker-bake.hcl'

env:
  REGISTRY: docker.io
  DOCKERHUB_NAMESPACE: tnyuma

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Metadata for basejudge
        id: meta-basejudge
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.DOCKERHUB_NAMESPACE }}/nextjudge-basejudge
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha

      - name: Build and push basejudge
        uses: docker/bake-action@v6
        with:
          files: docker-bake.hcl
          targets: basejudge
          push: true
          set: |
            basejudge.tags=${{ steps.meta-basejudge.outputs.tags }}
            basejudge.cache-from=type=gha
            basejudge.cache-to=type=gha,mode=max

      - name: Generate Metadata for core
        id: meta-core
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.DOCKERHUB_NAMESPACE }}/nextjudge-core
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha

      - name: Generate Metadata for judge
        id: meta-judge
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.DOCKERHUB_NAMESPACE }}/nextjudge-judge
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha

      - name: Build and push core and judge
        uses: docker/bake-action@v6
        with:
          files: docker-bake.hcl
          targets: core,judge
          push: true
          set: |
            core.tags=${{ steps.meta-core.outputs.tags }}
            judge.tags=${{ steps.meta-judge.outputs.tags }}
            core.cache-from=type=gha
            core.cache-to=type=gha,mode=max
            judge.cache-from=type=gha
            judge.cache-to=type=gha,mode=max
            judge.args.BASEJUDGE=${{ env.DOCKERHUB_NAMESPACE }}/nextjudge-basejudge:latest
            core.target=release
